name: CI

on:
  push:
    branches:
      - "master"
      - "main"
  pull_request:
    branches:
      - "master"
      - "main"
  schedule:
    # Run a cron job once daily
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.7"

          - os: ubuntu-latest
            python-version: "3.9"

          - os: macOS-latest
            python-version: "3.7"

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: experiments-binding-affinity
          channel-priority: true
          environment-file: environment.yml
          auto-activate-base: false

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Environment Information
        shell: bash -l {0}
        run: |
          conda info --all
          conda list

      - name: Run ligand featurization
        shell: bash -l {0}
        run: |
          python run_notebook.py features/featurize-template.ipynb features/example-ligand-only-chembl28-morgan512-1k-subsample.py --overwrite
          test -f features/example-ligand-only-chembl28-morgan512-1k-subsample/featurize.ipynb
          test -d features/example-ligand-only-chembl28-morgan512-1k-subsample/_output/

      - name: Run ligand experiment
        shell: bash -l {0}
        run: |
          python run_notebook.py experiments/torch-train-test-debug-template.ipynb experiments/000_example-ligand-only-chembl28-subset.py  --overwrite
          test -f experiments/000_example-ligand-only-chembl28-subset/torch-train-test-debug.ipynb
          test -d experiments/000_example-ligand-only-chembl28-subset/_output/
